import { View, Text, TouchableOpacity, TextInput, ScrollView, Modal, Alert, ActivityIndicator } from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { useState, useEffect } from 'react';
import { Save, Plus, X, Calendar } from 'lucide-react-native';
import { colors } from '../../lib/colors';
import { plotMapperAPI, PlotBlueprint } from '../../lib/api';
// Using expo-date-picker or simple date input

interface Zone {
  id: string;
  name: string;
  coordinates: { x1: number; y1: number; x2: number; y2: number };
  area: number;
  cropType?: string;
  plantingDate?: string;
  status?: 'PREPARING_SOIL' | 'YOUNG_SEEDLING' | 'IN_FULL_PRODUCTION' | 'HARVESTING' | 'FALLOW';
}

interface Partition {
  id: string;
  type: 'HORIZONTAL' | 'VERTICAL';
  position: number;
}

const CROP_TYPES = ['Jabuka', 'Malina', 'Borovnica', 'Kupina', 'Šljiva', 'Kruška', 'Trešnja'];
const CROP_STATUSES = [
  { value: 'PREPARING_SOIL', label: 'Priprema zemljišta' },
  { value: 'YOUNG_SEEDLING', label: 'Mlada sadnica' },
  { value: 'IN_FULL_PRODUCTION', label: 'U punom rodu' },
  { value: 'HARVESTING', label: 'Berba' },
  { value: 'FALLOW', label: 'Ugar' },
];

/**
 * Vera Plot Mapper Screen
 * Farmer digitalizes their parcel with zones and crop tagging
 */
export default function PlotMapperScreen() {
  const router = useRouter();
  const { parcelId } = useLocalSearchParams<{ parcelId: string }>();
  const [length, setLength] = useState('');
  const [width, setWidth] = useState('');
  const [zones, setZones] = useState<Zone[]>([]);
  const [partitions, setPartitions] = useState<Partition[]>([]);
  const [selectedZone, setSelectedZone] = useState<Zone | null>(null);
  const [showZoneModal, setShowZoneModal] = useState(false);
  const [partitionMode, setPartitionMode] = useState(false);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [showDatePicker, setShowDatePicker] = useState(false);

  // Zone form state
  const [zoneCropType, setZoneCropType] = useState('');
  const [zonePlantingDate, setZonePlantingDate] = useState(new Date());
  const [zoneStatus, setZoneStatus] = useState<string>('');

  // Canvas constants
  const canvasWidth = 300;
  const canvasHeight = 200;

  // Helper functions
  const calculateArea = (length: number, width: number): number => {
    return length * width;
  };

  useEffect(() => {
    if (parcelId) {
      loadBlueprint();
    }
  }, [parcelId]);

  // Auto-generate zones when dimensions or partitions change
  useEffect(() => {
    if (length && width && partitions.length > 0) {
      const l = parseFloat(length);
      const w = parseFloat(width);
      if (!isNaN(l) && !isNaN(w) && l > 0 && w > 0) {
        generateZones();
      }
    } else if (partitions.length === 0 && length && width) {
      // If no partitions, create single zone
      const l = parseFloat(length);
      const w = parseFloat(width);
      if (!isNaN(l) && !isNaN(w) && l > 0 && w > 0) {
        const totalArea = calculateArea(l, w);
        setZones([
          {
            id: 'zone-1',
            name: 'ZONA A',
            coordinates: { x1: 0, y1: 0, x2: canvasWidth, y2: canvasHeight },
            area: Math.round(totalArea),
          },
        ]);
      }
    }
  }, [length, width, partitions.length]);

  const loadBlueprint = async () => {
    if (!parcelId) return;
    setLoading(true);
    try {
      const blueprint = await plotMapperAPI.getByParcel(parcelId);
      if (blueprint) {
        setLength(blueprint.length.toString());
        setWidth(blueprint.width.toString());
        setZones(blueprint.blueprintData.zones || []);
        setPartitions(blueprint.blueprintData.partitions || []);
      }
    } catch (error) {
      console.error('Error loading blueprint:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleAddPartition = () => {
    setPartitionMode(true);
  };

  const handleCanvasPress = (event: any) => {
    if (!partitionMode) return;

    const { locationX, locationY } = event.nativeEvent;

    // Determine if horizontal or vertical partition
    const isHorizontal = locationY < canvasHeight / 2;
    const partition: Partition = {
      id: `partition-${Date.now()}`,
      type: isHorizontal ? 'HORIZONTAL' : 'VERTICAL',
      position: isHorizontal ? locationY : locationX,
    };

    const newPartitions = [...partitions, partition];
    setPartitions(newPartitions);
    setPartitionMode(false);
    
    // Zones will be auto-generated by useEffect
  };

  const generateZones = () => {
    if (!length || !width) return;

    const l = parseFloat(length);
    const w = parseFloat(width);
    if (isNaN(l) || isNaN(w)) return;

    const horizontalPartitions = partitions.filter(p => p.type === 'HORIZONTAL').sort((a, b) => a.position - b.position);
    const verticalPartitions = partitions.filter(p => p.type === 'VERTICAL').sort((a, b) => a.position - b.position);

    const newZones: Zone[] = [];
    const totalArea = calculateArea(l, w);
    
    // Calculate zone count
    const rows = horizontalPartitions.length + 1;
    const cols = verticalPartitions.length + 1;
    const zoneCount = rows * cols;
    const zoneArea = totalArea / zoneCount;

    // Calculate zone dimensions in meters
    const zoneWidth = w / cols;
    const zoneHeight = l / rows;

    let zoneIndex = 1;
    for (let row = 0; row < rows; row++) {
      for (let col = 0; col < cols; col++) {
        const zoneName = `ZONA ${String.fromCharCode(64 + zoneIndex)}`;
        
        // Calculate pixel coordinates for canvas
        const x1 = (col * canvasWidth) / cols;
        const y1 = (row * canvasHeight) / rows;
        const x2 = ((col + 1) * canvasWidth) / cols;
        const y2 = ((row + 1) * canvasHeight) / rows;

        // Check if zone already exists (preserve crop data)
        const existingZone = zones.find(z => 
          Math.abs(z.coordinates.x1 - x1) < 1 && 
          Math.abs(z.coordinates.y1 - y1) < 1
        );

        newZones.push({
          id: existingZone?.id || `zone-${zoneIndex}`,
          name: existingZone?.name || zoneName,
          coordinates: { x1, y1, x2, y2 },
          area: Math.round(zoneArea),
          cropType: existingZone?.cropType,
          plantingDate: existingZone?.plantingDate,
          status: existingZone?.status,
        });
        zoneIndex++;
      }
    }

    setZones(newZones);
  };

  const handleZonePress = (zone: Zone) => {
    setSelectedZone(zone);
    setZoneCropType(zone.cropType || '');
    setZonePlantingDate(zone.plantingDate ? new Date(zone.plantingDate) : new Date());
    setZoneStatus(zone.status || '');
    setShowZoneModal(true);
  };

  const handleSaveZone = () => {
    if (!selectedZone) return;

    const updatedZones = zones.map((z) =>
      z.id === selectedZone.id
        ? {
            ...z,
            cropType: zoneCropType,
            plantingDate: zonePlantingDate.toISOString(),
            status: zoneStatus as any,
          }
        : z
    );

    setZones(updatedZones);
    setShowZoneModal(false);
    setSelectedZone(null);
  };

  const handleSaveBlueprint = async () => {
    if (!parcelId) {
      Alert.alert('Error', 'Parcel ID is missing');
      return;
    }

    if (!length || !width) {
      Alert.alert('Required', 'Please enter length and width');
      return;
    }

    const l = parseFloat(length);
    const w = parseFloat(width);

    if (isNaN(l) || isNaN(w) || l <= 0 || w <= 0) {
      Alert.alert('Invalid', 'Please enter valid dimensions');
      return;
    }

    setSaving(true);
    try {
      await plotMapperAPI.save({
        parcelId,
        length: l,
        width: w,
        blueprintData: {
          zones,
          partitions,
        },
      });

      Alert.alert('Success', 'Blueprint saved successfully', [
        {
          text: 'OK',
          onPress: () => router.back(),
        },
      ]);
    } catch (error: any) {
      Alert.alert('Error', error.response?.data?.message || 'Failed to save blueprint');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <View style={{ flex: 1, backgroundColor: colors.background, justifyContent: 'center', alignItems: 'center' }}>
        <ActivityIndicator size="large" color={colors.primary} />
      </View>
    );
  }

  const totalArea = length && width ? calculateArea(parseFloat(length), parseFloat(width)) : 0;

  return (
    <View style={{ flex: 1, backgroundColor: colors.background }}>
      {/* Header */}
      <View style={{ padding: 20, borderBottomWidth: 0.5, borderBottomColor: colors.border }}>
        <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}>
          <Text style={{ fontSize: 16, fontWeight: '300', color: colors.text.primary, letterSpacing: 0.5 }}>
            Vera Plot Mapper
          </Text>
          <TouchableOpacity
            onPress={handleSaveBlueprint}
            disabled={saving}
            style={{
              paddingHorizontal: 16,
              paddingVertical: 8,
              backgroundColor: colors.primary,
              borderRadius: 6,
              flexDirection: 'row',
              alignItems: 'center',
              gap: 6,
            }}
            activeOpacity={0.7}
          >
            {saving ? (
              <ActivityIndicator size="small" color={colors.background} />
            ) : (
              <Save size={16} color={colors.background} strokeWidth={1} />
            )}
            <Text style={{ fontSize: 12, fontWeight: '400', color: colors.background, letterSpacing: 0.3 }}>
              Save Blueprint
            </Text>
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView style={{ flex: 1 }}>
        <View style={{ padding: 20 }}>
          {/* Dimensions Input */}
          <View style={{ marginBottom: 24 }}>
            <Text style={{ fontSize: 13, fontWeight: '400', color: colors.text.primary, marginBottom: 12, letterSpacing: 0.3 }}>
              Dimensions
            </Text>
            <View style={{ flexDirection: 'row', gap: 12 }}>
              <View style={{ flex: 1 }}>
                <Text style={{ fontSize: 11, fontWeight: '300', color: colors.text.secondary, marginBottom: 6 }}>
                  Length (m)
                </Text>
                <TextInput
                  value={length}
                  onChangeText={setLength}
                  placeholder="150"
                  keyboardType="decimal-pad"
                  style={{
                    padding: 12,
                    borderWidth: 0.5,
                    borderColor: colors.border,
                    borderRadius: 6,
                    backgroundColor: colors.surface,
                    fontSize: 13,
                    fontWeight: '300',
                    color: colors.text.primary,
                  }}
                />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={{ fontSize: 11, fontWeight: '300', color: colors.text.secondary, marginBottom: 6 }}>
                  Width (m)
                </Text>
                <TextInput
                  value={width}
                  onChangeText={setWidth}
                  placeholder="80"
                  keyboardType="decimal-pad"
                  style={{
                    padding: 12,
                    borderWidth: 0.5,
                    borderColor: colors.border,
                    borderRadius: 6,
                    backgroundColor: colors.surface,
                    fontSize: 13,
                    fontWeight: '300',
                    color: colors.text.primary,
                  }}
                />
              </View>
            </View>
            {totalArea > 0 && (
              <Text style={{ marginTop: 8, fontSize: 11, fontWeight: '300', color: colors.text.secondary }}>
                Total Area: {totalArea.toLocaleString()} m²
              </Text>
            )}
          </View>

          {/* Canvas */}
          <View style={{ marginBottom: 24 }}>
            <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
              <Text style={{ fontSize: 13, fontWeight: '400', color: colors.text.primary, letterSpacing: 0.3 }}>
                Plot Canvas
              </Text>
              <TouchableOpacity
                onPress={handleAddPartition}
                style={{
                  paddingHorizontal: 12,
                  paddingVertical: 6,
                  borderWidth: 0.5,
                  borderColor: colors.border,
                  borderRadius: 6,
                  flexDirection: 'row',
                  alignItems: 'center',
                  gap: 6,
                  backgroundColor: partitionMode ? `${colors.primary}10` : colors.surface,
                }}
                activeOpacity={0.7}
              >
                <Plus size={14} color={partitionMode ? colors.primary : colors.text.secondary} strokeWidth={1} />
                <Text
                  style={{
                    fontSize: 11,
                    fontWeight: '300',
                    color: partitionMode ? colors.primary : colors.text.secondary,
                  }}
                >
                  Add Partition
                </Text>
              </TouchableOpacity>
            </View>

            {/* Interactive Canvas */}
            <TouchableOpacity
              onPress={handleCanvasPress}
              activeOpacity={1}
              style={{
                width: canvasWidth,
                height: canvasHeight,
                backgroundColor: colors.surface,
                borderWidth: 0.5,
                borderColor: 'rgba(26, 48, 33, 0.2)',
                borderRadius: 6,
                position: 'relative',
                alignSelf: 'center',
              }}
            >
              {/* Grid Background */}
              <View style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 }}>
                {Array.from({ length: 20 }).map((_, i) => (
                  <View
                    key={`h-${i}`}
                    style={{
                      position: 'absolute',
                      top: (i * canvasHeight) / 20,
                      left: 0,
                      right: 0,
                      height: 0.5,
                      backgroundColor: 'rgba(26, 48, 33, 0.05)',
                    }}
                  />
                ))}
                {Array.from({ length: 15 }).map((_, i) => (
                  <View
                    key={`v-${i}`}
                    style={{
                      position: 'absolute',
                      left: (i * canvasWidth) / 15,
                      top: 0,
                      bottom: 0,
                      width: 0.5,
                      backgroundColor: 'rgba(26, 48, 33, 0.05)',
                    }}
                  />
                ))}
              </View>

              {/* Partitions (dashed lines) */}
              {partitions.map((partition) => (
                <View
                  key={partition.id}
                  style={{
                    position: 'absolute',
                    [partition.type === 'HORIZONTAL' ? 'top' : 'left']: partition.position,
                    [partition.type === 'HORIZONTAL' ? 'left' : 'top']: 0,
                    [partition.type === 'HORIZONTAL' ? 'width' : 'height']: partition.type === 'HORIZONTAL' ? canvasWidth : canvasHeight,
                    [partition.type === 'HORIZONTAL' ? 'height' : 'width']: 1,
                    borderWidth: 1,
                    borderColor: colors.primary,
                    borderStyle: 'dashed',
                  }}
                />
              ))}

              {/* Zones */}
              {zones.map((zone, index) => {
                const zoneWidth = canvasWidth / (partitions.filter(p => p.type === 'VERTICAL').length + 1);
                const zoneHeight = canvasHeight / (partitions.filter(p => p.type === 'HORIZONTAL').length + 1);
                const col = index % (partitions.filter(p => p.type === 'VERTICAL').length + 1);
                const row = Math.floor(index / (partitions.filter(p => p.type === 'VERTICAL').length + 1));

                return (
                  <TouchableOpacity
                    key={zone.id}
                    onPress={() => handleZonePress(zone)}
                    style={{
                      position: 'absolute',
                      left: col * zoneWidth,
                      top: row * zoneHeight,
                      width: zoneWidth,
                      height: zoneHeight,
                      borderWidth: 0.5,
                      borderColor: colors.primary,
                      backgroundColor: zone.cropType ? `${colors.primary}05` : 'transparent',
                      padding: 4,
                    }}
                    activeOpacity={0.7}
                  >
                    <Text
                      style={{
                        fontSize: 9,
                        fontWeight: '300',
                        color: colors.text.primary,
                        letterSpacing: 0.2,
                      }}
                      numberOfLines={2}
                    >
                      {zone.name}
                    </Text>
                    {zone.cropType && (
                      <Text
                        style={{
                          fontSize: 8,
                          fontWeight: '300',
                          color: colors.text.secondary,
                          marginTop: 2,
                        }}
                        numberOfLines={1}
                      >
                        {zone.cropType}
                      </Text>
                    )}
                    <Text
                      style={{
                        fontSize: 7,
                        fontWeight: '300',
                        color: colors.text.secondary,
                        marginTop: 1,
                      }}
                    >
                      {zone.area} m²
                    </Text>
                  </TouchableOpacity>
                );
              })}

              {/* Dimensions Labels */}
              {length && width && (
                <>
                  <View style={{ position: 'absolute', top: -20, left: canvasWidth / 2 - 20 }}>
                    <Text style={{ fontSize: 10, fontWeight: '300', color: colors.text.secondary }}>
                      {length}m
                    </Text>
                  </View>
                  <View style={{ position: 'absolute', left: -40, top: canvasHeight / 2 - 8 }}>
                    <Text style={{ fontSize: 10, fontWeight: '300', color: colors.text.secondary }}>
                      {width}m
                    </Text>
                  </View>
                </>
              )}
            </TouchableOpacity>

            {partitionMode && (
              <Text style={{ marginTop: 8, fontSize: 11, fontWeight: '300', color: colors.primary, textAlign: 'center' }}>
                Tap on canvas to add partition line
              </Text>
            )}
          </View>

          {/* Zones List */}
          {zones.length > 0 && (
            <View>
              <Text style={{ fontSize: 13, fontWeight: '400', color: colors.text.primary, marginBottom: 12, letterSpacing: 0.3 }}>
                Zones ({zones.length})
              </Text>
              {zones.map((zone) => (
                <TouchableOpacity
                  key={zone.id}
                  onPress={() => handleZonePress(zone)}
                  style={{
                    padding: 12,
                    borderWidth: 0.5,
                    borderColor: colors.border,
                    borderRadius: 6,
                    backgroundColor: colors.surface,
                    marginBottom: 8,
                  }}
                  activeOpacity={0.7}
                >
                  <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
                    <View style={{ flex: 1 }}>
                      <Text style={{ fontSize: 12, fontWeight: '300', color: colors.text.primary, letterSpacing: 0.2 }}>
                        {zone.name}
                      </Text>
                      {zone.cropType && (
                        <Text style={{ fontSize: 11, fontWeight: '300', color: colors.text.secondary, marginTop: 2 }}>
                          {zone.cropType} • {zone.area} m²
                        </Text>
                      )}
                      {!zone.cropType && (
                        <Text style={{ fontSize: 11, fontWeight: '300', color: colors.text.secondary, marginTop: 2 }}>
                          {zone.area} m² • Tap to add crop
                        </Text>
                      )}
                    </View>
                  </View>
                </TouchableOpacity>
              ))}
            </View>
          )}
        </View>
      </ScrollView>

      {/* Zone Modal */}
      <Modal visible={showZoneModal} transparent animationType="slide">
        <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' }}>
          <View style={{ backgroundColor: colors.background, borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 20 }}>
            <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }}>
              <Text style={{ fontSize: 16, fontWeight: '300', color: colors.text.primary, letterSpacing: 0.5 }}>
                {selectedZone?.name}
              </Text>
              <TouchableOpacity onPress={() => setShowZoneModal(false)}>
                <X size={20} color={colors.text.secondary} strokeWidth={1} />
              </TouchableOpacity>
            </View>

            <ScrollView>
              {/* Crop Type */}
              <View style={{ marginBottom: 16 }}>
                <Text style={{ fontSize: 11, fontWeight: '300', color: colors.text.secondary, marginBottom: 6 }}>
                  Crop Type
                </Text>
                <ScrollView horizontal showsHorizontalScrollIndicator={false}>
                  <View style={{ flexDirection: 'row', gap: 8 }}>
                    {CROP_TYPES.map((crop) => (
                      <TouchableOpacity
                        key={crop}
                        onPress={() => setZoneCropType(crop)}
                        style={{
                          paddingHorizontal: 12,
                          paddingVertical: 8,
                          borderWidth: 0.5,
                          borderColor: zoneCropType === crop ? colors.primary : colors.border,
                          borderRadius: 6,
                          backgroundColor: zoneCropType === crop ? `${colors.primary}10` : colors.surface,
                        }}
                        activeOpacity={0.7}
                      >
                        <Text
                          style={{
                            fontSize: 11,
                            fontWeight: '300',
                            color: zoneCropType === crop ? colors.primary : colors.text.secondary,
                          }}
                        >
                          {crop}
                        </Text>
                      </TouchableOpacity>
                    ))}
                  </View>
                </ScrollView>
              </View>

              {/* Planting Date */}
              <View style={{ marginBottom: 16 }}>
                <Text style={{ fontSize: 11, fontWeight: '300', color: colors.text.secondary, marginBottom: 6 }}>
                  Planting Date
                </Text>
                <TouchableOpacity
                  onPress={() => setShowDatePicker(true)}
                  style={{
                    padding: 12,
                    borderWidth: 0.5,
                    borderColor: colors.border,
                    borderRadius: 6,
                    backgroundColor: colors.surface,
                    flexDirection: 'row',
                    alignItems: 'center',
                    gap: 8,
                  }}
                  activeOpacity={0.7}
                >
                  <Calendar size={16} color={colors.text.secondary} strokeWidth={1} />
                  <Text style={{ fontSize: 13, fontWeight: '300', color: colors.text.primary }}>
                    {zonePlantingDate.toLocaleDateString('sr-RS')}
                  </Text>
                </TouchableOpacity>
              </View>

              {/* Status */}
              <View style={{ marginBottom: 20 }}>
                <Text style={{ fontSize: 11, fontWeight: '300', color: colors.text.secondary, marginBottom: 6 }}>
                  Status
                </Text>
                <View style={{ gap: 8 }}>
                  {CROP_STATUSES.map((status) => (
                    <TouchableOpacity
                      key={status.value}
                      onPress={() => setZoneStatus(status.value)}
                      style={{
                        padding: 12,
                        borderWidth: 0.5,
                        borderColor: zoneStatus === status.value ? colors.primary : colors.border,
                        borderRadius: 6,
                        backgroundColor: zoneStatus === status.value ? `${colors.primary}10` : colors.surface,
                      }}
                      activeOpacity={0.7}
                    >
                      <Text
                        style={{
                          fontSize: 12,
                          fontWeight: '300',
                          color: zoneStatus === status.value ? colors.primary : colors.text.secondary,
                        }}
                      >
                        {status.label}
                      </Text>
                    </TouchableOpacity>
                  ))}
                </View>
              </View>

              <TouchableOpacity
                onPress={handleSaveZone}
                style={{
                  backgroundColor: colors.primary,
                  paddingVertical: 14,
                  borderRadius: 6,
                  alignItems: 'center',
                }}
                activeOpacity={0.7}
              >
                <Text style={{ fontSize: 14, fontWeight: '400', color: colors.background, letterSpacing: 0.5 }}>
                  Save Zone
                </Text>
              </TouchableOpacity>
            </ScrollView>
          </View>
        </View>
      </Modal>

      {/* Date Picker Modal */}
      {showDatePicker && (
        <Modal visible={showDatePicker} transparent animationType="fade">
          <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' }}>
            <View style={{ backgroundColor: colors.background, borderRadius: 8, padding: 20, width: '80%' }}>
              <Text style={{ fontSize: 14, fontWeight: '300', color: colors.text.primary, marginBottom: 16 }}>
                Select Planting Date
              </Text>
              <TextInput
                value={zonePlantingDate.toISOString().split('T')[0]}
                onChangeText={(text) => {
                  const date = new Date(text);
                  if (!isNaN(date.getTime())) {
                    setZonePlantingDate(date);
                  }
                }}
                placeholder="YYYY-MM-DD"
                style={{
                  padding: 12,
                  borderWidth: 0.5,
                  borderColor: colors.border,
                  borderRadius: 6,
                  backgroundColor: colors.surface,
                  fontSize: 13,
                  fontWeight: '300',
                  color: colors.text.primary,
                  marginBottom: 16,
                }}
              />
              <TouchableOpacity
                onPress={() => setShowDatePicker(false)}
                style={{
                  backgroundColor: colors.primary,
                  paddingVertical: 12,
                  borderRadius: 6,
                  alignItems: 'center',
                }}
              >
                <Text style={{ fontSize: 13, fontWeight: '400', color: colors.background }}>
                  Confirm
                </Text>
              </TouchableOpacity>
            </View>
          </View>
        </Modal>
      )}
    </View>
  );
}
