/**
 * Part B — “full film” programme depth (English).
 * Maps to diligence sections: problem, solution, mechanics, market, competition, business model, scaling, impact, team, finances.
 * Numeric ranges are discussion scaffolding; bind them to chartered models and audited data before formal submission.
 */
import type { TechnicalProposalChapter } from "@/content/technical-proposal.part-a";

export const TECHNICAL_PROPOSAL_PROGRAMME_PART_B: readonly TechnicalProposalChapter[] = [
  {
    id: "pb-01-problem-detailed",
    title: "Part B — 1. The problem",
    paragraphs: [
      "Competent growers are often under-paid by documentation, not by farming. Field books, chats, spreadsheets and carrier messages rarely share one batch identity, so reconstructing answers for auditors or buyers steals days every season—and SKU holds and dispute write-downs hit everyone when stories diverge.",
      "Retail procurement cannot defend modern organic SKU programmes from certificate screenshots alone. Without machine-checkable inputs, polygons, custody and cold evidence tied together, QA teams borrow margin through manual reconciliation or accept opaque risk.",
      "Refrigerated logistics multiplies weak points: consolidation, waits, borders, final delivery. Where custody lives only in informal messaging, honest handlers still lose disputes—and finance cannot align payments with temperature timelines reliably.",
      "Southeast Europe offers strong horticulture upside for diversified EU sourcing, yet tools that assume permanent connectivity and homogeneous devices exclude mature operators. Bio Vera intervenes between field truth, logistics truth and shelf truth—where money is lost today.",
    ],
  },
  {
    id: "pb-02-solution-technology",
    title: "Part B — 2. The solution (programme model)",
    paragraphs: [
      "Bio Vera binds inputs, cultivation, packing, sanctioned packaging, refrigerated movement and buyer dossiers into one operational programme—not a slogan. Compliant growers can qualify for retail-oriented fulfilment; converters and authorised suppliers anchor programme-grade packaging SKUs; missions and handovers expose custody explicitly.",
      "Software carries identifiers and timestamps consistently offline and online so events are not orphaned. Integrity rules block or explain disallowed chemistry, bad identity or implausible geography; settlement logic can reference the same batch timeline as QA, reducing treasury drift.",
      "Partnership is pilot-based: KPI contracts on completeness, passports and discrepancy rates—not raw listing proliferation. Corridor expansion follows SKU and handshake readiness, not marketing spray.",
      "Underlying storage is relational (PostgreSQL via Prisma): estates and parcels with geometry; treatments and seeds; batches with QA, freshness and telemetry; missions and handovers; orders and splits—so auditors can trace graphs, not orphaned PDFs.",
    ],
  },
  {
    id: "pb-03-how-it-works-technical",
    title: "Part B — 3. How it works (mechanisms)",
    paragraphs: [
      "People sign in via role-guarded API access on web and mobile. Chemically sensitive writes pass central validation against approved catalogues before persistence—shortcuts via alternate routes cannot bypass that policy layer.",
      "Growers capture evidence offline-first where signal is thin; payloads sync in bounded batches. GPS samples align with authorised estate footprint; malformed or late-but-valid rows are separated for review without corrupting dossiers quietly.",
      "Batch lineage ties pickups, checkpoints, thermometer trails, handshake records and conformity photography to each programme’s explicit standards. Commerce rows carry grower, driver and platform splits referencing the same batch graph auditors already view.",
      "Operations run with structured logs, sane rate limits around authentication and dossier probing, staged strictness via configuration, and multilingual presentation over stable IDs. The condensed Implementation atlas below summarizes HTTP surfaces engineers use when wiring partners.",
    ],
  },
  {
    id: "pb-04-market-numbers",
    title: "Part B — 4. Market (quantified framing)",
    paragraphs: [
      "Product focus today targets SKUs where category buyers already demand verifiable cold narratives (soft fruit, leafy lines, premium organics)—programme configuration encodes default temperature bands and packaging photo expectations (`bio_vera_standards`) aligning marketing claims with QA scripts rather than generic “farm app” horizontalism.",
      "European fresh and chilled horticulture procurement aggregates to large multi-billion-euro annual baskets across modern retail; speciality, organic and protected-origin lines justify higher documentation spend per tonne than undifferentiated commodities—binding filings should cite licensed industry statistics. Vera deliberately chases programme wedges where QA already rewards proof density rather than generic TAM vanity.",
      "Beachhead hypothesis: Southeastern European exporters capable of refrigerated integrity into German distribution represent a scalable pool—from hundreds toward low-thousands of commercial-grade estates over several seasonal windows—addressable via pilot cohort onboarding rather than broadcast acquisition.",
      "Operational addressable depth: each onboarded estate can fan out dozens of parcels, hundreds of treatments and multiple seasonal announcements—pricing models weight programme fees against mission telemetry density and buyer passport consumption rather than naïvely per-seat grower SaaS metrics alone.",
      "Buyer SKU programme uplift remains explicitly contingent on dossier KPIs—not slide optimism: exemplar bands (e.g. EUR 35–110M contingent baskets after multiple seasons) belong only in chartered FP&A worksheets referencing named retailers with proper attribution.",
      "Logistics attach rate: refrigerated missions per batch programme often span multiple legs per seasonal SKU wave—telemetry completeness targets drive integration priorities before raw route optimisation ambitions.",
      "Digital adoption precondition: handset OS matrix minimums published each release anticipating Android-majority corridor demographics—device lab budgets sized accordingly.",
      "Sensitivity: halving achievable estate throughput pushes break-even horizons—Part B finances section aligns scenario toggles.",
      "Data governance note: externally facing market assertions in binding submissions must cite third-party datasets (Eurostat derivatives, Nielsen-family extracts if licensed, trade association compilations)—this document supplies structural placeholders only.",
    ],
  },
  {
    id: "pb-05-competition",
    title: "Part B — 5. Competitive landscape",
    paragraphs: [
      "Incumbent categories include (i) generic farm management SaaS optimised for Anglo-American row crops—not refrigerated passport synthesis; (ii) transport visibility TMS slices lacking cultivation-phase chemistry joins; (iii) certificate-marketplaces layering marketing gloss atop weak event graphs; (iv) blockchain vanity proofs lacking ergonomics under offline constraints.",
      "Adjacent ERP and WMS integrations remain necessary plumbing yet rarely unify grower polygons, refrigerated custody and retail QR dossiers under one deterministic batch ontology—integrations become satellite feeds feeding Vera’s lineage rather than competitors replicating entirety.",
      "Buyer-built internal trace teams solve point problems but seldom externalise repeatable corridor tooling for supplier ecosystems—Vera monetises coherence across suppliers instead of reinventing dashboards per retailer silo.",
      "Differentiation thesis: deterministic offline ingestion plus Integrity Guard intersections plus phased economic narration projecting into passport—not a maximalist blockchain claim nor a glorified spreadsheet cloud.",
      "Switching friction favours pragmatic exporters once dossier discrepancy KPI improves—risk is pilot fatigue if early cohort promises overshoot interoperability realities; phased gates mitigate hype debt.",
      "Partnership coopetition stance: sanctioned supplier storefronts coexist with whitelist governance—commercial competitors on inputs may interoperate programmatically rather than walled-garden exclusions when safety rules align.",
      "Governance optics: neutrality on inputs except safety programme rules fosters trust versus retailer-captive captive catalogue plays that sceptical growers perceive as margin capture.",
      "Technical moat layering emphasises deterministic sync regression discipline and audit artefacts rivals cannot trivially imitate without multi-year corpus investment—yet humility: moat sustains via execution velocity and cohort satisfaction, not slide bullets alone.",
    ],
  },
  {
    id: "pb-06-business-model",
    title: "Part B — 6. Business model",
    paragraphs: [
      "Revenue composes programmatic platform uplift segmented by SKU waves, logistical orchestration premiums where corridors demand managed visibility, ancillary insurance commissioning where corridor law and partner underwriting permit such legs, differentiated seed/input economics exploiting partner pricing vs standard tiers (`users.isVeraPartner`) with hectares tracked via `discount_quota_usage`, optional premium dossier/analytics exports gated by buyer contracts—not raw personal-data vending.",
      "Grower remuneration improvements arise via faster listing readiness, Vera bonus payouts tied to substantiated packing compliance snapshots, lowered dispute-driven write-downs—all monetising behavioural change rather than abstract seat counts alone.",
      "Unit economics scaffolding (see finances section) distinguishes contribution margin before central R&D carve-outs; cohort-level CAC equivalents blend field enablement trainers and onboarding travel—not pure digital CPL semantics.",
      "Treasury segregation principle: escrow float handling never informally overlaps operating cash forecasts—custodial discipline is both ethics and fiduciary narrative for institutional partners.",
      "Cross-subsidy guardrails discourage predatory onboarding of estates unlikely to assemble EU dossiers—gatekeeping aligns commercial incentives with stewardship outcomes programmatically touted.",
      "Long-term annuity thesis: deepening SKU lineage density inside existing buyer programmes yields expansion revenue minus marginal incremental infra cost curves—bounded by Postgres query tuning milestone referenced in roadmap annex.",
      "Dynamic seed/partner posture maps to authoritative user flags (`users.isVeraPartner`) with discount quotas (`discount_quota_usage` tying hectares to concession integrity) ensuring partner economics remain queryable—not handshake-only anecdotes.",
      "Upside optionality includes certified logistics circle expansion billed as compliance-grade networks rather than commodity freight arbitrage—a brand premium defensible inside procurement scorecards emphasizing custody proof density.",
      "Commercial humility: illustrative figures remain non-binding placeholders until chartered finance aligns historical pilot ledger actuals.",
    ],
  },
  {
    id: "pb-07-scaling-eu-global",
    title: "Part B — 7. Scaling (EU depth and disciplined global posture)",
    paragraphs: [
      "European scaling prioritises depth: repeatable corridor templates (estate ingestion playbooks SR/DE, logistics handshake RACI doubles, DPIA artefacts per geography) replicated before widening SKUs arbitrarily—preventing brittle horizontal sprawl collapsing dossier coherence.",
      "Wave sequencing runs Baltic–Adriatic pilot depth first, Rhine–North diffusion with Hamburg retail anchors next, then southern expansion only when handshake telemetry benchmarks justify it—geographic labels are indicative, not fixed roadshow claims.",
      "Regulatory stack harmonisation tracks GDPR operational maturity, SCC/DPA inventories for cross-border grower dossier consumption, refrigeration evidence admissibility practices evolving under buyer QA—not attempting harmonised global statute replacement.",
      "Language expansion acknowledges retail corridors (FR/ES complements existing EN/SR/DE emphasis) strictly via professional glossary-controlled translation—not raw machine mistranslation of chemical identifiers.",
      "Global posture remains selective: opportunistic buyer-led corridors (e.g. Latin American sourcing programmes feeding EU passports) entertained only where custody instrumentation parity can be stipulated contractually—no vanity flag-map expansion absent handshake feasibility.",
      "Technical scale levers include read replica strategies for dossier assembly hotspots, chunked sync payload budgets per estate tier, catastrophe recovery drills escalating annually from tabletop to restore exercises—documented resilience reduces buyer onboarding drag.",
      "People scale embeds fractional domain desks until each pilot geography staffs corridor owner translating agronomic idioms faithfully into schema constraints growers cannot game accidentally.",
      "Partner ecosystem leverage recruits certified fleets and cold-store operators adhering to Integrity-adjacent SOP versioning—scaling network effects hinge on behavioural standards not raw node count KPI alone.",
      "Humility clause: geopolitical disruptions (trade friction, subsidy regime shifts) may compress corridor throughput plans—financial sensitivities articulate downside toggles openly.",
      "Measurement: each geography exit-criteria checklist (operational KPI green + legal posture green + grower cohort satisfaction baseline) gates marketing amplification spend—avoid hype-led geographic marketing debt.",
      "Capital allocation bias toward corridor ROI density rather than broad conference branding yields compounding dossier completeness reputation capital among procurement circles sensitive to retrospective audit embarrassment risk.",
      "Innovation scouting on spectroscopy aides or interoperable GS1 deepening remains exploratory—core scaling thesis stays deterministic ingestion and custody structuring before speculative science layers.",
      "Ultimately EU scaling earns global optionality because passport credibility recognized by sophisticated buyers lowers incremental trust acquisition cost abroad—provided domestic execution remains exemplary first.",
    ],
  },
  {
    id: "pb-08-impact-climate-economy",
    title: "Part B — 8. Impact (climate, economy, society)",
    paragraphs: [
      "Climate-linked accountability improves when refrigerated deviations expose timestamped excursions rather than annualised backward-averaged marketing claims—enabling truthful buyer narratives and punitive correction where chronic drift appears.",
      "Shortened documentation loops indirectly trim wasted harvest rejections stemming from retrospective paperwork failures unrelated to intrinsic quality—reducing spoilage footprints attributable to bureaucracy rather than agronomy.",
      "Economic inclusion: conscientious SMEs gain negotiating leverage resembling larger integrated exporters possessing in-house dossier teams—compressing oligopsony information advantages slowly if programmes scale ethically without predatory onboarding.",
      "Rural resilience benefits when younger professionals perceive digitised stewardship careers as respectable—countering hollowed-out valley demographics stressing EU peripheral regions.",
      "Macro measurement discipline: attributable CO₂ deltas require baselined longitudinal studies versus control estates under an explicit study design; Vera commits archiving anonymised aggregate telemetry suitable for consortium climate reporting—not premature retail badge confection.",
      "Logistics optimisation secondary effects curtail redundant emergency airfreight substitutions born of mistrust outages—hypothesis contingent on telemetry proving fewer panic reroutes.",
      "Social ergonomics lowers digital exclusion friction for ageing operators respecting large typography, optional audio cues—human-centred KPI not traditionally appearing in carbons-focused decks yet material to adoption fidelity.",
      "Risk framing: overstated eco claims backlash could damage credibility—marketing governance reviews tie consumer-facing wording to dossier subgraph coverage thresholds before release stamping.",
      "Balanced humility: Vera cannot singularly solve planetary heating; incremental integrity improvements aggregate inside category programmes whose collective buyer leverage dwarfs any single agritech slogan.",
      "Partnership synergy with insurance companions may incentivise loss-reduction tooling adoption—potential secondary societal benefit via stabilised farmer liquidity contingent on permissible regulatory corridors.",
      "Urban consumer trust loops close when Hamburg retail narratives align with cryptographic-grade batch identifiers consumers can optionally interrogate—not theatrical stock imagery substitutes.",
      "Socio-economic feedback monitoring tracks grower churn post-first-settlement, gendered adoption variance (trainer recruitment sensitivity), multilingual support ticket composition—preventing monocultural blindness undermining inclusivity pledges rhetoric-only.",
      "Environmental justice lens: dossier coherence helps smaller producers resist displacement by industrial actors wielding paralegal armies—ethical positioning aligned with subsidy philosophical underpinnings even absent quantified deltas early.",
      "Integrated summary: impactful when measured honestly—economy first via fairer monetisation pathways for proof-rich growers; climate second via truthful cold-chain artefacts and spoilage avoidance; society via inclusion ergonomics—all requiring ongoing empirical discipline not launch-day hero metrics.",
    ],
  },
  {
    id: "pb-09-team",
    title: "Part B — 9. Team",
    paragraphs: [
      "Core engineering emphasises pragmatic TypeScript delivery across Nest, Next, Expo, Prisma—avoiding gratuitous polyglot fragmentation that onboarding friction multiplies for institutional acquirers valuing codebase continuity.",
      "Product attaches qualitative research cycles anchored in grower usability labs validating scanner ergonomics, harvest-day cognitive load—not desktop-only heuristic reviews detached from grime realities.",
      "Domain liaisons spanning agronomic QA translators, refrigerated logistics veterans and treasury-aligned analysts embed vocabulary precision into schema migrations—preventing brittle abstractions coined in isolation from operators.",
      "Security and compliance desk maintains rotating ownership on escrow narration modules and dossier merges—paired programming mitigates key-person existential risk prized by diligence committees.",
      "Localisation desk enforces glossary discipline forbidding chemically ambiguous machine translation outputs—particularly German/Serbian regulatory nuance divergence corridors.",
      "Advisory scaffolding (legal DP, chartered finance external, category buyer alumni) complements leadership without crowding executing squads—the ratio is tuned per funding stage as the board directs.",
      "Founder narrative bridging communications discipline with multi-year Vera brand evolution informs external storytelling credibility—not operational substitute for delegated engineering leadership scalability.",
      "Recruiting ethos weights systems empathy interviewing alongside algorithms—avoid monoculture optimise-only mindsets brittle under humane field variability.",
      "HR continuity codifies shadow documentation weeks before departing senior owners rotate—preventing folklore loss triggering regressions auditors rediscover painfully later.",
      "Leadership moderation restrains heroic overtime cultures degrading incident quality—sustainable pacing treated as fiduciary not indulgence paradoxically protecting uptime reliability.",
      "Equity inclusivity ambitions submitted to periodic board DEI checkpoints rather than hollow statements—risk argument emphasises cognitive diversity surfacing QA edge-case failures earlier homogeneous teams discount.",
      "Operational transparency: RACI artefacts per rollout wave delineate escalation paths—preventing existential confusion during refrigerated dispute weekends requiring executive arbitration clarity.",
      "Closing reflection: calibre measured by cohort promoter scores among growers/drivers—not vanity conference speaker tally—aligning reputational KPI with mission authenticity.",
    ],
  },
  {
    id: "pb-10-finances",
    title: "Part B — 10. Finances (discussion scaffolding)",
    paragraphs: [
      "DISCLAIMER: numbers scaffold discussion—not forecasts; chartered accountants, auditors and corridor-specific counsel must replace placeholders before underwriting, subsidy certification or regulated offering contexts.",
      "Engineering/product steady-state payroll band (annualised illustrative): EUR 680k–1.05m covering blended 7–11 FTE equivalents including QA automation and periodic UX ethnography—not raw headcount fetish.",
      "Managed infrastructure envelopes: EUR 42k–95k/year for Postgres tiers, CDN, transactional mail, observability ingest—scaled stepwise alongside dossier read traffic inflection milestones.",
      "Corridor instrumentation capital (IoT gateways, certified integration surcharges amortised early SKU waves): aggregated EUR 80k–200k illustrative unless partner-provided substitutions reduce capex intensity.",
      "Revenue plateau sensitivity (monthly recurring illustrative post-36 month horizon contingent on SKU density and escrow-linked economics): EUR 180k–320k—upper bound assumes minimal regulatory friction unlocking insurance commissioning legs legally.",
      "Break-even interplay: delaying buyer handshake completeness two quarters sequentially triggers expense throttling playbook (hiring freeze, marketing pause) preserving runway humility—preventing reckless narrative persistence versus empirical KPI divergence.",
      "Working capital segregation: escrow float accounting templates isolate custodial liquidity from ops runway modelling—financial statement clarity demanded by treasury partners underwriting pilot expansion debt facilities hypothetically.",
      "Sensitivity qualitative matrix: favourable tailwinds faster buyer dossier reliance adoption; adverse headwinds regulatory insurance linkage blockage, geopolitical tariff shocks escalating hedging burdens not numerically enumerated herein superficially.",
      "Capital expenditure policy bias expensing R&D payroll unless auditor directs discrete capitalisation—conservative optics for early-stage subsidy reviewers sceptical intangible asset inflation artistry.",
      "Exit-readiness housekeeping: orderly data portability commitments ensure growers retain structured exports—balancing commercial stickiness ethically without hostage narratives undermining goodwill valuation multiples hypothetically pursued later.",
      "Scenario toggles hypothetical: pessimistic trims revenue plateau 35% lengthening cash-out date 6–11 months illustrative; optimistic accelerates plateau arrival yet strains hiring pipeline risking quality debt—risk committee monitors trade-offs quarterly.",
      "Grant stacking discipline documents non-double-funding exposures when EU cohesion instruments overlap corridor pilots—preventing retrospective clawback nightmares discovered mid-audit painfully.",
      "Audit trail alignment internally mirrors external diligence: immutable references tie financial hypotheses back to enumerated operational KPI assumptions—preventing orphaned spreadsheet mythology detached from dossier completeness realities.",
      "Board reporting rhythm surfaces rolling thirteen-week liquidity outlook alongside cohort handshake completeness KPI—forcing finance and operational truth convergence monthly not quarterly folklore drift.",
      "Final prudential note: any single illustrative band cherry-picked out of context misleads—investors and grant bodies must ingest entire structured narrative including risk register correlations before probabilistic judgement formation.",
    ],
  },
] as const;
