/**
 * Part B — “full film” programme depth (English).
 * Maps to diligence sections: problem, solution, mechanics, market, competition, business model, scaling, impact, team, finances.
 * Numeric ranges marked [ILLUSTRATIVE] are placeholders for chartered models and audited data.
 */
import type { TechnicalProposalChapter } from "@/content/technical-proposal.part-a";

export const TECHNICAL_PROPOSAL_PROGRAMME_PART_B: readonly TechnicalProposalChapter[] = [
  {
    id: "pb-01-problem-detailed",
    title: "Part B — 1. The problem (detailed analysis)",
    paragraphs: [
      "Small and mid-scale growers who already meet or aspire to EU-grade practices are structurally under-rewarded: their constraint is not agronomy but evidentiary friction. Every season they reproduce the same story in incompatible formats—paper field books, photos in chat apps, ad hoc temperature notes from carriers, and finance spreadsheets that were never joined to the same batch identity. When a buyer or auditor asks a precise question (“which input on which parcel on which day, and who held this temperature?”), reconstructing truth becomes a project parallel to harvesting itself.",
      "Procurement organisations face the mirror pain. Category managers are asked to certify origin, sustainability postures and cold-chain continuity for SKU programmes that exceed what generic certificates can defend. Screenshots forwarded by intermediaries do not compose into machine-checkable dossiers; incident response during a QA hold cannot rely on folklore. The organisation either accepts residual opacity or staffs large manual reconciliation—not because colleagues are unwilling, but because the data model was never unified.",
      "Logistics sits on the hinge. Refrigerated corridors multiply handovers: consolidation points, customs pauses, cross-docks, last-mile arrivals. Custody timelines that live only in unstructured messages create disputes that destroy margin for everyone—even when physical handling was diligent. Nobody benefits from ambiguity except opportunistic middle layers that arbitrage information asymmetry.",
      "Regional asymmetry exacerbates everything. Southeastern European corridors offer competitive horticulture potential and diversification value for EU retail, yet legacy digitisation stacks assumed continuous cloud connectivity and young smartphone-only demographics. Offline gaps on picking routes silently exclude competent operators unless tooling tolerates intermittent towers and deliberate human ergonomics.",
      "Programme economics worsen the optics. Buyers reward documentation-rich suppliers with listings and repeats; growers without repeatable dossiers default to distressed spot markets. Vera’s thesis is structural: conscientious growers should monetise stewardship through shared proof, not through parallel compliance theatre recreated per buyer.",
      "Regulatory tightening is directional even where exact timelines differ by SKU: expectations for trace inputs, refrigerated evidence, allergen-critical packaging genealogy and retrospective auditability converge. Narrative marketing without chronological joins between inputs, polygons, QA events and shipments becomes brittle under plausible stress scenarios—not hypothetical far futures but everyday category QA.",
      "Summary diagnosis: fragmentation of identity, time and custody across spreadsheets, chats and departmental tools is not an IT inconvenience; it misprices competent producers and taxes buyers with latent liability. Bio Vera intervenes where the organisational scar tissue is deepest—between field truth, logistics truth and retail truth.",
    ],
  },
  {
    id: "pb-02-solution-technology",
    title: "Part B — 2. The solution (technology and operating model)",
    paragraphs: [
      "Bio Vera proposes a vertically integrated digital programme: software plus operating choreography that binds the cultivation-to-retail loop into one evidence spine. Seeds and sanctioned inputs connect to InsurancePolicy companions where permissible; cultivation evidence carries geo and integrity checks; compliant packaging earns documented bonuses; refrigerated missions emit structured custody objects; Hamburg-facing retail artefacts (QR dossiers built on deterministic Batch lineage) summarise what auditors already see internally.",
      "Technology role is fiduciary to that spine—not to replace growers or inspectors, but to ensure no honest event is orphaned for lack of a consistent identifier or sync path. Core stack (Next.js surfaces, Expo mobile, Nest APIs, Postgres/Prisma, offline IndexedDB/SQLite first-write patterns) trades novelty for reproducibility.",
      "Integrity Guard operationalises whitelist and barcode coherence rules so unauthorised chemistry cannot quietly enter dossiers; geo predicates align field entries with Estate polygon boundaries—blocking or explaining rejects with humane UX rather than silent corruption.",
      "Financial narration mirrors custody: escrow-style phased releases and splits (grower plus Vera bonus segments, logistics, platform uplift from seed margins and commissions where modeled) cite the same batch chronology QA uses—shrinking divergence between treasury story and refrigeration story.",
      "Partnership framing: corridors launch as cohort pilots with explicit KPI contracts (handshake completeness, passport consumption, dossier discrepancy rates); expansion is SKU-programme gated rather than indiscriminate listing growth.",
      "Compared to episodic SaaS tooling, Vera’s operating model asserts end-to-end ownership of the dossier artefact—even when third-party TMS or telemetry devices integrate, they ingest as typed events fused to lineage, never as orphaned attachments.",
    ],
  },
  {
    id: "pb-03-how-it-works-technical",
    title: "Part B — 3. How it works (technical mechanics)",
    paragraphs: [
      "Actors authenticate through JWT-bearing clients; guards enforce discrete roles spanning growers, logistics partners, fleet operatives, buyers, admins. Sensitive mutations emit audit-grade logs with correlation identifiers for investigations.",
      "Growers onboard Estates with authoritative polygon geometries; cultivation capture (entries, QA-adjacent events, harvesting/pack transitions) persists locally under weak connectivity using optimistic queues, idempotent tokens and deterministic merge semantics that prefer additive facts over ambiguous last-writer-wins on measured quantities.",
      "Integrity Guard validations intersect domain tables: sanctioned fertiliser chemistry against BioWhiteList barcodes where enabled; SeedBatch.serialNumber coherence for barcode-scanned propagation; coarse GPS predicates ensuring evidence geotags reconcile to declared estate envelopes—surfacing rejection reasons to operators.",
      "Batch minting freezes immutable genealogy anchors; packaging and compliance artefacts attach as typed edges; missions model refrigerated legs with checkpoints and explicit handovers so custody gaps become data exceptions instead of conversational disputes.",
      "Public-facing passport projections selectively redact while preserving narrative integrity—buyers consume timelines derived from authoritative internal graphs without exporting entire operational databases.",
      "Observability: structured logging, rate limiting around authentication and dossier probing, health checks enabling degraded read-only dossier delivery when feasible; regression suites gate releases alongside cohort acceptance criteria documented for pilots.",
      "Internationalisation separates locale presentation from invariant identifiers—dossiers remain stable regardless of Serbian, German or English UX shells elsewhere on the ecosystem.",
      "Operational toggles segregate staging permissiveness from production strictness; feature flags degrade enforcement surfaces without rewriting historical timelines when buyer freeze events demand reversibility discipline.",
      "Technical honesty: certain admin instruments may mature web-first if policy-risk profile supports it—grower and logistics-critical paths insist on cross-surface parity as policy mandates.",
      "Taken together the mechanics articulate a single slogan engineering can audit: deterministic identifiers offline-first ingestion integrity-filtered payloads structured custody phased economic narration projecting verifiable dossiers outward.",
    ],
  },
  {
    id: "pb-04-market-numbers",
    title: "Part B — 4. Market (quantified framing [ILLUSTRATIVE])",
    paragraphs: [
      "European fresh and chilled horticulture procurement exceeds tens of billions of euros annually consolidated across multiple retail organisations; SKU-level speciality and organic lines grow faster than mass conventional categories where differentiated origin stories defend margin [ILLUSTRATIVE macro band cited from consortium desk research—not audited herein]. Vera targets programme slices—not “all food”—focused on corridors where dossier completeness already gates listing decisions.",
      "Beachhead hypothesis: Southeastern European exporters capable of refrigerated integrity into German distribution clock represent [ILLUSTRATIVE: hundreds to low-thousands of commercial-grade estates transitioning across three to five seasonal windows] addressable via pilot cohort onboarding rather than broadcast acquisition.",
      "Buyer-side penetration model assumes two discreet retail archetypes piloting passports early (discounter QA rigour vs speciality narration depth) yielding combined annual SKU programme lift [ILLUSTRATIVE: EUR 35–110M contingent basket] only after handshake completeness KPI stabilises—not day-one inference.",
      "Logistics attach rate: refrigerated missions per batch programme forecast [ILLUSTRATIVE: median 4–11 legs per seasonal SKU wave] implying telemetry completeness targets drive integration priorities before raw route optimisation ambitions.",
      "Digital adoption precondition: handset OS matrix minimums published each release anticipating [ILLUSTRATIVE: Android share >80% corridor-weighted demographic]—device lab budgets sized accordingly.",
      "Sensitivity: halving achievable estate throughput pushes break-even horizons—Part B finances section aligns scenario toggles.",
      "Data governance note: externally facing market assertions in binding submissions must cite third-party datasets (Eurostat derivatives, Nielsen-family extracts if licensed, trade association compilations)—this document supplies structural placeholders only.",
    ],
  },
  {
    id: "pb-05-competition",
    title: "Part B — 5. Competitive landscape",
    paragraphs: [
      "Incumbent categories include (i) generic farm management SaaS optimised for Anglo-American row crops—not refrigerated passport synthesis; (ii) transport visibility TMS slices lacking cultivation-phase chemistry joins; (iii) certificate-marketplaces layering marketing gloss atop weak event graphs; (iv) blockchain vanity proofs lacking ergonomics under offline constraints.",
      "Adjacent ERP and WMS integrations remain necessary plumbing yet rarely unify grower polygons, refrigerated custody and retail QR dossiers under one deterministic batch ontology—integrations become satellite feeds feeding Vera’s lineage rather than competitors replicating entirety.",
      "Buyer-built internal trace teams solve point problems but seldom externalise repeatable corridor tooling for supplier ecosystems—Vera monetises coherence across suppliers instead of reinventing dashboards per retailer silo.",
      "Differentiation thesis: deterministic offline ingestion plus Integrity Guard intersections plus phased economic narration projecting into passport—not a maximalist blockchain claim nor a glorified spreadsheet cloud.",
      "Switching friction favours pragmatic exporters once dossier discrepancy KPI improves—risk is pilot fatigue if early cohort promises overshoot interoperability realities; phased gates mitigate hype debt.",
      "Partnership coopetition stance: sanctioned supplier storefronts coexist with whitelist governance—commercial competitors on inputs may interoperate programmatically rather than walled-garden exclusions when safety rules align.",
      "Governance optics: neutrality on inputs except safety programme rules fosters trust versus retailer-captive captive catalogue plays that sceptical growers perceive as margin capture.",
      "Technical moat layering emphasises deterministic sync regression discipline and audit artefacts rivals cannot trivially imitate without multi-year corpus investment—yet humility: moat sustains via execution velocity and cohort satisfaction, not slide bullets alone.",
    ],
  },
  {
    id: "pb-06-business-model",
    title: "Part B — 6. Business model",
    paragraphs: [
      "Revenue composes programmatic platform uplift segmented by SKU waves, logistical orchestration premiums where corridors demand managed visibility, ancillary insurance commissioning where InsurancePolicy linkage remains legally viable, differentiated seed/input economics exploiting partner pricing vs standard tiers (capturing constructive margin ethically disclosed to growers within programme FAQs), optional premium analytics dossier exports gated by buyer contracts—not raw personal data vending.",
      "Grower remuneration improvements arise via faster listing readiness, Vera bonus payouts tied to substantiated packing compliance snapshots, lowered dispute-driven write-downs—all monetising behavioural change rather than abstract seat counts alone.",
      "Unit economics scaffolding (see finances section) distinguishes contribution margin before central R&D carve-outs; cohort-level CAC equivalents blend field enablement trainers and onboarding travel—not pure digital CPL semantics.",
      "Treasury segregation principle: escrow float handling never informally overlaps operating cash forecasts—custodial discipline is both ethics and fiduciary narrative for institutional partners.",
      "Cross-subsidy guardrails discourage predatory onboarding of estates unlikely to assemble EU dossiers—gatekeeping aligns commercial incentives with stewardship outcomes programmatically touted.",
      "Long-term annuity thesis: deepening SKU lineage density inside existing buyer programmes yields expansion revenue minus marginal incremental infra cost curves—bounded by Postgres query tuning milestone referenced in roadmap annex.",
      "Partnership rebates (if enacted) disclosed transparently lest programme trust erodes; dynamic seed pricing honours User.isVeraPartner distinction without covert cross-subsidies hidden from cultivation participants.",
      "Upside optionality includes certified logistics circle expansion billed as compliance-grade networks rather than commodity freight arbitrage—a brand premium defensible inside procurement scorecards emphasizing custody proof density.",
      "Commercial humility: illustrative figures remain non-binding placeholders until chartered finance aligns historical pilot ledger actuals.",
    ],
  },
  {
    id: "pb-07-scaling-eu-global",
    title: "Part B — 7. Scaling (EU depth and disciplined global posture)",
    paragraphs: [
      "European scaling prioritises depth: repeatable corridor templates (estate ingestion playbooks SR/DE, logistics handshake RACI doubles, DPIA artefacts per geography) replicated before widening SKUs arbitrarily—preventing brittle horizontal sprawl collapsing dossier coherence.",
      "Wave sequencing: Baltic-Adriatic pilot spine → Rhine-North diffusion leveraging Hamburg retail anchor hypotheses → contingent southern expansion gated on handshake telemetry maturity benchmarks [ILLUSTRATIVE wave labels only].",
      "Regulatory stack harmonisation tracks GDPR operational maturity, SCC/DPA inventories for cross-border grower dossier consumption, refrigeration evidence admissibility practices evolving under buyer QA—not attempting harmonised global statute replacement.",
      "Language expansion acknowledges retail corridors (FR/ES complements existing EN/SR/DE emphasis) strictly via professional glossary-controlled translation—not raw machine mistranslation of chemical identifiers.",
      "Global posture remains selective: opportunistic buyer-led corridors (e.g. Latin American sourcing programmes feeding EU passports) entertained only where custody instrumentation parity can be stipulated contractually—no vanity flag-map expansion absent handshake feasibility.",
      "Technical scale levers include read replica strategies for dossier assembly hotspots, chunked sync payload budgets per estate tier, catastrophe recovery drills escalating annually from tabletop to restore exercises—documented resilience reduces buyer onboarding drag.",
      "People scale embeds fractional domain desks until each pilot geography staffs corridor owner translating agronomic idioms faithfully into schema constraints growers cannot game accidentally.",
      "Partner ecosystem leverage recruits certified fleets and cold-store operators adhering to Integrity-adjacent SOP versioning—scaling network effects hinge on behavioural standards not raw node count KPI alone.",
      "Humility clause: geopolitical disruptions (trade friction, subsidy regime shifts) may compress corridor throughput plans—financial sensitivities articulate downside toggles openly.",
      "Measurement: each geography exit-criteria checklist (operational KPI green + legal posture green + grower cohort satisfaction baseline) gates marketing amplification spend—avoid hype-led geographic marketing debt.",
      "Capital allocation bias toward corridor ROI density rather than broad conference branding yields compounding dossier completeness reputation capital among procurement circles sensitive to retrospective audit embarrassment risk.",
      "Innovation scouting on spectroscopy aides or interoperable GS1 deepening remains exploratory—core scaling thesis stays deterministic ingestion and custody structuring before speculative science layers.",
      "Ultimately EU scaling earns global optionality because passport credibility recognized by sophisticated buyers lowers incremental trust acquisition cost abroad—provided domestic execution remains exemplary first.",
    ],
  },
  {
    id: "pb-08-impact-climate-economy",
    title: "Part B — 8. Impact (climate, economy, society)",
    paragraphs: [
      "Climate-linked accountability improves when refrigerated deviations expose timestamped excursions rather than annualised backward-averaged marketing claims—enabling truthful buyer narratives and punitive correction where chronic drift appears.",
      "Shortened documentation loops indirectly trim wasted harvest rejections stemming from retrospective paperwork failures unrelated to intrinsic quality—reducing spoilage footprints attributable to bureaucracy rather than agronomy.",
      "Economic inclusion: conscientious SMEs gain negotiating leverage resembling larger integrated exporters possessing in-house dossier teams—compressing oligopsony information advantages slowly if programmes scale ethically without predatory onboarding.",
      "Rural resilience benefits when younger professionals perceive digitised stewardship careers as respectable—countering hollowed-out valley demographics stressing EU peripheral regions.",
      "Macro measurement discipline: attributable CO₂ deltas require baselined longitudinal studies versus control estates [STUDY ACTION]; Vera commits archiving anonymised aggregate telemetry suitable for consortium climate reporting—not premature retail badge confection.",
      "Logistics optimisation secondary effects curtail redundant emergency airfreight substitutions born of mistrust outages—hypothesis contingent on telemetry proving fewer panic reroutes.",
      "Social ergonomics lowers digital exclusion friction for ageing operators respecting large typography, optional audio cues—human-centred KPI not traditionally appearing in carbons-focused decks yet material to adoption fidelity.",
      "Risk framing: overstated eco claims backlash could damage credibility—marketing governance reviews tie consumer-facing wording to dossier subgraph coverage thresholds before release stamping.",
      "Balanced humility: Vera cannot singularly solve planetary heating; incremental integrity improvements aggregate inside category programmes whose collective buyer leverage dwarfs any single agritech slogan.",
      "Partnership synergy with insurance companions may incentivise loss-reduction tooling adoption—potential secondary societal benefit via stabilised farmer liquidity contingent on permissible regulatory corridors.",
      "Urban consumer trust loops close when Hamburg retail narratives align with cryptographic-grade batch identifiers consumers can optionally interrogate—not theatrical stock imagery substitutes.",
      "Socio-economic feedback monitoring tracks grower churn post-first-settlement, gendered adoption variance (trainer recruitment sensitivity), multilingual support ticket composition—preventing monocultural blindness undermining inclusivity pledges rhetoric-only.",
      "Environmental justice lens: dossier coherence helps smaller producers resist displacement by industrial actors wielding paralegal armies—ethical positioning aligned with subsidy philosophical underpinnings even absent quantified deltas early.",
      "Integrated summary: impactful when measured honestly—economy first via fairer monetisation pathways for proof-rich growers; climate second via truthful cold-chain artefacts and spoilage avoidance; society via inclusion ergonomics—all requiring ongoing empirical discipline not launch-day hero metrics.",
    ],
  },
  {
    id: "pb-09-team",
    title: "Part B — 9. Team",
    paragraphs: [
      "Core engineering emphasises pragmatic TypeScript delivery across Nest, Next, Expo, Prisma—avoiding gratuitous polyglot fragmentation that onboarding friction multiplies for institutional acquirers valuing codebase continuity.",
      "Product attaches qualitative research cycles anchored in grower usability labs validating scanner ergonomics, harvest-day cognitive load—not desktop-only heuristic reviews detached from grime realities.",
      "Domain liaisons spanning agronomic QA translators, refrigerated logistics veterans and treasury-aligned analysts embed vocabulary precision into schema migrations—preventing brittle abstractions coined in isolation from operators.",
      "Security and compliance desk maintains rotating ownership on escrow narration modules and dossier merges—paired programming mitigates key-person existential risk prized by diligence committees.",
      "Localisation desk enforces glossary discipline forbidding chemically ambiguous machine translation outputs—particularly German/Serbian regulatory nuance divergence corridors.",
      "Advisory scaffolding (legal DP, chartered finance external, category buyer alumni) complements leadership without crowding executing squads—the ratio tuned per funding stage milestones [BOARD GOVERNANCE].",
      "Founder narrative bridging communications discipline with multi-year Vera brand evolution informs external storytelling credibility—not operational substitute for delegated engineering leadership scalability.",
      "Recruiting ethos weights systems empathy interviewing alongside algorithms—avoid monoculture optimise-only mindsets brittle under humane field variability.",
      "HR continuity codifies shadow documentation weeks before departing senior owners rotate—preventing folklore loss triggering regressions auditors rediscover painfully later.",
      "Leadership moderation restrains heroic overtime cultures degrading incident quality—sustainable pacing treated as fiduciary not indulgence paradoxically protecting uptime reliability.",
      "Equity inclusivity ambitions submitted to periodic board DEI checkpoints rather than hollow statements—risk argument emphasises cognitive diversity surfacing QA edge-case failures earlier homogeneous teams discount.",
      "Operational transparency: RACI artefacts per rollout wave delineate escalation paths—preventing existential confusion during refrigerated dispute weekends requiring executive arbitration clarity.",
      "Closing reflection: calibre measured by cohort promoter scores among growers/drivers—not vanity conference speaker tally—aligning reputational KPI with mission authenticity.",
    ],
  },
  {
    id: "pb-10-finances",
    title: "Part B — 10. Finances [ILLUSTRATIVE]",
    paragraphs: [
      "DISCLAIMER: numbers scaffold discussion—not forecasts; chartered accountants, auditors and corridor-specific counsel must replace placeholders before underwriting, subsidy certification or regulated offering contexts.",
      "Engineering/product steady-state payroll band (annualised illustrative): EUR 680k–1.05m covering blended 7–11 FTE equivalents including QA automation and periodic UX ethnography—not raw headcount fetish.",
      "Managed infrastructure envelopes: EUR 42k–95k/year for Postgres tiers, CDN, transactional mail, observability ingest—scaled stepwise alongside dossier read traffic inflection milestones.",
      "Corridor instrumentation capital (IoT gateways, certified integration surcharges amortised early SKU waves): aggregated EUR 80k–200k illustrative unless partner-provided substitutions reduce capex intensity.",
      "Revenue plateau sensitivity (monthly recurring illustrative post-36 month horizon contingent on SKU density and escrow-linked economics): EUR 180k–320k—upper bound assumes minimal regulatory friction unlocking insurance commissioning legs legally.",
      "Break-even interplay: delaying buyer handshake completeness two quarters sequentially triggers expense throttling playbook (hiring freeze, marketing pause) preserving runway humility—preventing reckless narrative persistence versus empirical KPI divergence.",
      "Working capital segregation: escrow float accounting templates isolate custodial liquidity from ops runway modelling—financial statement clarity demanded by treasury partners underwriting pilot expansion debt facilities hypothetically.",
      "Sensitivity qualitative matrix: favourable tailwinds faster buyer dossier reliance adoption; adverse headwinds regulatory insurance linkage blockage, geopolitical tariff shocks escalating hedging burdens not numerically enumerated herein superficially.",
      "Capital expenditure policy bias expensing R&D payroll unless auditor directs discrete capitalisation—conservative optics for early-stage subsidy reviewers sceptical intangible asset inflation artistry.",
      "Exit-readiness housekeeping: orderly data portability commitments ensure growers retain structured exports—balancing commercial stickiness ethically without hostage narratives undermining goodwill valuation multiples hypothetically pursued later.",
      "Scenario toggles hypothetical: pessimistic trims revenue plateau 35% lengthening cash-out date 6–11 months illustrative; optimistic accelerates plateau arrival yet strains hiring pipeline risking quality debt—risk committee monitors trade-offs quarterly.",
      "Grant stacking discipline documents non-double-funding exposures when EU cohesion instruments overlap corridor pilots—preventing retrospective clawback nightmares discovered mid-audit painfully.",
      "Audit trail alignment internally mirrors external diligence: immutable references tie financial hypotheses back to enumerated operational KPI assumptions—preventing orphaned spreadsheet mythology detached from dossier completeness realities.",
      "Board reporting rhythm surfaces rolling thirteen-week liquidity outlook alongside cohort handshake completeness KPI—forcing finance and operational truth convergence monthly not quarterly folklore drift.",
      "Final prudential note: any single illustrative band cherry-picked out of context misleads—investors and grant bodies must ingest entire structured narrative including risk register correlations before probabilistic judgement formation.",
    ],
  },
] as const;
