import type { TechnicalProposalChapter } from "@/content/technical-proposal.part-a";

export const TECHNICAL_PROPOSAL_CHAPTERS_PART_D: readonly TechnicalProposalChapter[] = [
  {
    id: "tp-requirements-deep",
    title: "19. Requirements depth, verification evidence and lifecycle governance",
    paragraphs: [
      "Programme-aligned requirements catalogue under Bio Vera is organised as orthogonal tracks: behavioural (what growers, logistics and buyers shall obtain), invariant (identifiers, ordering, cryptographic hygiene), temporal (ordering of custody and settlement hints) and declarative governance (whitelist families, SKU programme overlays). Tracks cross-link so a single backlog item seldom mutates one dimension without cascading review—reducing regressions masked as benign copy edits that accidentally relax enforcement.",
      "Each accepted requirement inherits a canonical code (e.g. BV-INV-0412) anchored in Markdown living documents versioned beside migrations. Acceptance tests cite these codes explicitly; exploratory sessions log candidate gaps as BV-INV-NEW-* until triage merges or rejects them against programme scope. Automated export scripts emit CSV artefacts for auditors mapping codes to sprint velocity and deployment tags to prove traceability—not snapshot theatre regenerated once yearly.",
      "Non-functional overlays specify envelope constraints: dossier projections must hydrate under agreed P95 latencies measured from edge POPs geographically representative of Baltic–Adriatic corridors; outage windows require read-only dossier degrade mode respecting consumer transparency mandates while blocking mutating reconciliation actions that could fork financial truth offline.",
      "Verification evidence hierarchy ranks from unit proofs (financial split edge cases mirroring escrow segments) through integrated API harnesses seeded with pseudonymous fixtures to full offline chaos drills where scripted DNS blackholes validate SQLite outbox flushing without duplicate mission completion tokens. Each tier feeds a release gate matrix; hotfix bypass demands executive risk acceptance memos with shelf life limits.",
      "Lifecycle governance mandates retirement of deprecated requirement codes only after sunset telemetry shows zero active clients depending on removed fields for two consecutive release trains or explicit partner waivers under contract addenda. Orphaned codes otherwise decay documentation trust—hence automated lint sweeps fail CI when OpenAPI schema fields lack mapping rows in the traceability sheet.",
      "Human factors requirements capture minimum font sizes, contrast ratios and haptic confirmation toggles for mobile scanning devices used with gloves; these sit alongside technical integrity rules to avoid “compliant but unusable” outcomes that trigger shadow processes outside the audited stack.",
      "Operational verification includes synthetic mission insertions flagged as non-commercial so dashboards segment noise from cohort pilots; divergence beyond tolerance thresholds raise reliability incidents even if outward customer impact nil—preventing dormant metric rot prior to exponential traffic inflection.",
    ],
  },
  {
    id: "tp-grower-deep",
    title: "20. Grower solution depth — onboarding, polygons, Integrity Guard interplay and ergonomics",
    paragraphs: [
      "Estate onboarding combines administrative capture (beneficial actors, authorised mobile devices lists, optional commercial agent linkage) with geospatial artefacts: polygons submitted as GeoJSON-derived structures validated server-side against self-intersection budgets and minimum vertex density safeguards to prevent spoofed micron-boundaries circumventing pesticide proximity rules tied to neighbouring parcels when regulatory overlays exist.",
      "Integrity Guard ingestion paths branch: chemistry events assert whitelist membership keyed on normalised SKU plus batch serial references; deviations produce structured denies with escalation vectors (appeal uploads, provisional programme grace windows, admin adjudication dashboards). Seeds and packaging artefacts receive parallel guardrails aligning with Vera Partner distinction rules when enabled so economic incentives never silently downgrade enforcement strictness purely for uptake optics.",
      "Harvest declarations enforce mass conservation heuristics and timestamp monotonic sanity relative to plantation phenology priors seeded per crop family—surfacing outliers for agronomist review instead of brute blocking unless policy severity demands hard stops. Imagery uploads embed EXIF sanitisation stripping EXIF vectors that historically leaked sensitive geodata while retaining coarse capture windows for auditors.",
      "Packaging coherence surfaces translate programme crate/punnet/film enumerations into human metaphors (‘returnable Vera crate’) while mapping machine codes for downstream scanners. Unknown scans trigger lightweight suggestion engines consulting recent historical acceptance patterns—not ML black boxes absent governance—preventing orphaned SKUs accumulating in dormant tables unbeknownst to finance depreciation schedules.",
      "Offline UX sequences minimise modal depth during rain or glove operations: affirmative actions enlarged, destructive actions gated by secondary confirmations with optional biometric future hook but never mandatory in baseline compliance with accessibility doctrines. Telemetry summarises abandonment funnels anonymously to guide iterative microcopy—not personally identifiable keystroke taps.",
      "Collaborative stewardship allows invited agronomists limited scoped windows to annotate events without treasury privileges; revocation propagates pessimistically onto devices asynchronously with signed edge tokens expiring cleanly to minimise stale collaborator surfaces lingering after relationship termination.",
      "Regionalisation overlays adjust date formats yet avoid ambiguous fiscal week boundaries tied to payouts; settlement hints render in programme currency tiers with disclaimers distinguishing indicative projections from irrevocable confirmations pending buyer acceptance gates.",
      "Synthetic persona lab reviews pair designers with practising growers quarterly to regress assumptions about literacy, glare and cold-hand numbness ergonomics—instrumental to avoiding cosmetically perfect yet field-hostile workflows.",
    ],
  },
  {
    id: "tp-logistics-deep",
    title: "21. Logistics depth — missions, refrigeration semantics, multimodal corridors and treasury adjacency",
    paragraphs: [
      "Mission authoring stitches batch pickup commitments, permissible delay budgets and refrigerated setpoints differentiated by SKU families (berries vs leafy constraints). Trucks receive mission bundles including handshake QR entropy seeds resisting trivial replay under snapshot photography attacks; rotations occur per corridor security posture reviews.",
      "Waypoint tolerances degrade gracefully under traffic reality: probabilistic ETA adjustments bubble to growers’ dashboards ethically without leaking competitive carrier benchmarking where antitrust sensitivities flagged by counsel exist. Passive geolocation jitter policies align with minimise-data doctrine while preserving sufficient fidelity for QA reconstructions.",
      "Cold-chain semantics discriminate sensor hardware classes: calibrated digital loggers versus analogue fallback readings flagged as degraded trust tier in passports unless dual corroborated. Aggregation windows compress high-frequency bursts into succinct envelope charts for consumer readability while archiving raw granularity for adjudication horizons defined contractually.",
      "Multimodal future-proofing stubs rail or short-sea adjunct legs as optional subgraph nodes without forcing premature schema churn when pilots remain trucking-first. Border dwell events annotate customs narrative sections distinct from refrigeration charts to prevent spurious correlations mistaken for negligent cooling.",
      "Incident drills rehearse simultaneous temperature spike plus partial RFID pallet mismatch—forcing operators through structured decision trees culminating in irrevocable disqualification artefacts or rehabilitative corrective plans with timelines. Artefacts propagate to treasury shadow ledgers flagged until finance human sign-off aligns with QA closure.",
      "Finance adjacency forbids rewriting custody graphs when solely adjusting VAT display layers; versioning partitions annotate fiscal interpretation changes separately from factual movement edges to uphold evidentiary layering principles valued by German retail audit partners historically sceptical of merged narratives.",
      "Operational excellence metrics quantify handshake completion ratios, reconciliation latency between carrier POD scans and warehouse WMS ingestion when integrated, and discrepancy half-life until root-cause tagging—informing roadmap prioritisation more than superficial trip counts.",
    ],
  },
  {
    id: "tp-buyer-passport-deep",
    title: "22. Passport depth — dossier fusion, ontology bridges, scraping resistance and multilingual projection",
    paragraphs: [
      "Dossier fusion layers internal immutable lineage graphs with permissible marketing enrichments flagged explicitly as editorial versus structural. Divergence triggers engineering alerts if editorial copy cites scientific claims unmatched by attestations whitelisted in programme configuration—guarding against greenwashing drift post initial approval.",
      "Ontology bridges map internal chemical families to retailer procurement taxonomies using maintained synonym tables versioned as migratory artefacts; stale mappings fail closed to generic safe descriptors rather than hallucinated precision. Third-party ontology imports receive integrity checksum validation on ingest.",
      "Anti-scraping layers combine humane rate pacing, probabilistic tarpitting on abusive ASNs per SOC policy, optional mutual-TLS dossier tiers for wholesale partners and cryptographic capability tokens amortising brute PDF export attempts lacking legitimate API keys scoped to SKU families.",
      "Multilingual projections swap consumer lexica while conserving canonical chemical identifiers and batch codes in Latin character sets universally to avoid collation collisions during multinational assortment merges—a subtle failure mode underestimated in naive translation pipelines.",
      "Progressive disclosure stacks narrate ethically: shopper sees summarised reassurance; authenticated buyer peels operational charts; auditors obtain raw appendices including signature metadata if contractually mandated. Disclosure tier transitions log pseudonymous consumption metrics guiding future condensation heuristics without exposing individual shopper browsing dossiers improperly.",
      "Offline degradations for refrigerated retail kiosks (air-gapped tastings) utilise pre-signed dossier artefacts with embedded expiry resisting indefinite replay while maintaining authenticity within event windows—optional programme module gated behind explicit contractual acceptance of residual replay windows.",
      "SKU harmonisation diff visualisations spotlight pending retailer mapping conflicts before dossier freeze deadlines—preventing frantic hotfix Fridays destabilising production releases ahead of promotional campaigns.",
      "Historical diff viewers compare two batch revisions emphasising deltas to custody arcs and chemical attestations—not trivial layout shifts—focused on adjudicative ergonomics prized by QA leads.",
      "Consent surfaces communicate use of aggregated environmental commentary clearly separating measured vs interpolated metrics; conservative defaults withhold speculative climate narrative unless corroborating third-party metering contracts exist.",
    ],
  },
] as const;
